spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local
  application:
    name: apigateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # user-service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST,DELETE,PATCH,GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # product-service
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
            - Method=GET,POST,PUT
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}

        # order-service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=PUT,GET,POST,DELETE
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

server:
  port: 8000

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, beans



