spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/${LOCAL_DB_DATABASE}
    username: ${LOCAL_DB_ROOT_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  application:
    name: order-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Redisson 설정
redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"  
     
